
spring.application.name=courseRegister
server.port=${PORT:8080}



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.data-source-properties.allowPublicKeyRetrieval=true
spring.datasource.hikari.data-source-properties.useSSL=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cloudinary.cloud_name=dqfenqegx
cloudinary.api_key=645715196639127
cloudinary.api_secret=EdBZ-41_fqG6TUp_PU9MhB7APYY


spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#spring.profiles.active=dev